version: '3.8'

services:
  gw:
    image: nginx:latest
    container_name: l0g1n-gw
    ports:
      - "${GW_HTTP_PORT}:80"
      - "${GW_HTTPS_PORT}:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      - l0g1n-network

  db:
    image: postgres:15
    container_name: l0g1n-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - l0g1n-network

  api:
    build: ./api
    container_name: l0g1n-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PW}
      PORT: 8080
    networks:
      - l0g1n-network

volumes:
  db-data:

networks:
  l0g1n-network:
    driver: bridge